In [2]:
l1 = [0,1,2,3,4,5,6,7,8,9]
l2 = l1[:3]
print(l2)


[0, 1, 2]


In [3]:
print(l1[2:4])

[2, 3]


In [4]:
print(l1[4:])

[4, 5, 6, 7, 8, 9]


In [6]:
print(l1[:-2])

[0, 1, 2, 3, 4, 5, 6, 7]


In [7]:
print(l1[4::2])

[4, 6, 8]


In [8]:
print(l1[4::-2])

[4, 2, 0]


In [9]:
print(l1[::-1])

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [32]:
m1=[[0,1,2,3],[4,5,6,7],[8,9,10,11]]
print(m1)

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


In [26]:
print(m1[:][1])
print(m1[1][:])

[4, 5, 6, 7]
[4, 5, 6, 7]


In [27]:
print(m1[:])

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


In [28]:
print([x[1] for x in m1])

[1, 5, 9]


In [33]:
import numpy as np
m2 = np.array(m1)
print(m2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [34]:
print(m2[:,1])

[1 5 9]


In [31]:
print(m2[1:3,1:3])

[[ 5  6]
 [ 9 10]]


In [35]:
print(m2[1])

[4 5 6 7]


In [45]:
print(m1*2)

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


In [46]:
print(m2*2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [40]:
from math import prod
def fact(n):
    return prod([x for x in range(1,n+1)])
print(fact(5))

120


In [44]:
print([y for x in range(10)  for y in range(3) if x%2==0]*2)


[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]
